### ISSUE TITLE
Fix lint error in register.go

### ISSUE THREAD

**Issue by Akash4927** [openebs/node-disk-manager#102]
File: [register.go](https://github.com/openebs/node-disk-manager/blob/master/pkg/apis/openebs.io/register.go)

```
Line 4: warning: exported const GroupName should have comment (or a comment on this block) or be unexported (golint)
```

**Comment by andreathniah** [comment]
Hi there, can I try working on this issue?

**Comment by Akash4927** [comment]
@andreathniah Sure, please go ahead
