### ISSUE TITLE
Fix lint errors in eventhandler.go

### ISSUE THREAD

**Issue by Akash4927** [openebs/node-disk-manager#104]
File: [eventhandler.go](https://github.com/openebs/node-disk-manager/blob/master/cmd/probe/eventhandler.go)

```
Line 25: warning: exported type EventAction should have comment or be unexported (golint)
Line 28: warning: exported const AttachEA should have comment (or a comment on this block) or be unexported (golint)
```

**Comment by Abby3017** [comment]
can i take this task

**Comment by Akash4927** [comment]
Sure @Abby3017, please go ahead

**Comment by vivex** [comment]
https://github.com/openebs/node-disk-manager/pull/122 

this issue can be closed
