### ISSUE TITLE
Fix lint error in util.go

### ISSUE THREAD

**Issue by Akash4927** [openebs/node-disk-manager#107]
File: [util.go](https://github.com/openebs/node-disk-manager/blob/master/pkg/util/util.go)

```
Line 108: warning: comment on exported function Hash should be of the form "Hash ..." (golint)
```

**Comment by rafa-acioly** [comment]
can i take this one @Akash4927 ?

**Comment by rafa-acioly** [comment]
i've send you a PR (#116)

**Comment by Akash4927** [comment]
@rafa-acioly Thanks for the PR
