### ISSUE TITLE
Fix typo in scsicommands.go

### ISSUE THREAD

**Issue by Akash4927** [openebs/node-disk-manager#109]
File: [scsicommands.go](https://github.com/openebs/node-disk-manager/blob/master/pkg/smart/scsicommands.go)

```
Line 76: warning: "occured" is a misspelling of "occurred" (misspell)
```

**Comment by i-vikash** [comment]
I'd like to work on it

**Comment by Akash4927** [comment]
@i-vikash 
Sure, please go ahead.
