### ISSUE TITLE
Implement handlers for storagepoolclaim (SPC) events

### ISSUE THREAD

**Issue by kmova** [openebs/node-disk-manager#11]
node-disk-manager (ndm) custom controller has to watch for the SPC requests. This will be an initial implementation that takes into account the  following:
- add, update, delete handlers on the SPC object should be implemented
- consider the scenarios of SPC objects getting created when the node-disk-manager is not yet running (either not started or is restarting)
- follow the best practices around implementing the kubernetes custom controller to watch custom resource watchers - like having a cache store

**Comment by akhilerm** [comment]
Closing as NDM design has been changed and there will be separate controllers watching for pool custom resources.
