### ISSUE TITLE
Fix go vet error in types.go

### ISSUE THREAD

**Issue by Akash4927** [openebs/node-disk-manager#110]
File: [types.go](https://github.com/openebs/node-disk-manager/blob/master/pkg/apis/openebs.io/v1alpha1/types.go)

```
Line 16: error: struct field tag `json:"metadata, omitempty"` not compatible with reflect.StructTag.Get: suspicious space in struct tag value (vet)
```

**Comment by rbo13** [comment]
Hi @Akash4927, can I take this issue if no one is taking :)

**Comment by shindakun** [comment]
Will grab this one as well.

**Comment by Akash4927** [comment]
@rbo13 Please go ahead
@shindakun Please grab other issue
