### ISSUE TITLE
Implement creation of storagepool (SP) of type=ext4

### ISSUE THREAD

**Issue by kmova** [openebs/node-disk-manager#12]
In response to a StoragePoolClaim (SPC) with type=ext4, **_ndm_** will have to check for the Disks on the node where it is running and if the conditions mentioned in the SPC are satisfied, the ndm will have to:
- Identify a disk that matches the criteria mentioned in the SPC
- Format the disk with ext4
- Mount it in the specified location 
- Create a StoragePool (SP) custom resource, tie it with the host-labels and push it into the Kubernetes etcd. 

Please refer to #1 for the format of the SPC and SP

Some of the challenges that need to be handled:
- Propagating the mount from inside the container to host
- Testing the container for different versions of the kernel/OS

**Comment by gkGaneshR** [comment]
User need to enable mount propogation flag, only then mounting from within container will be visible outside. Minikube offers that flag to be setup while starting cluster. kubeadm is not yet providing that feature. We can't change it dynamically while the cluster is running else it'll crash the cluster, owing to liveness probe and readiness probe mismatch. ndm can't handle this until now.

**Comment by akhilerm** [comment]
The design has been changed. Now the Storage pool creation will be done by the SPC controller / CSPC operator and not by NDM.
