### ISSUE TITLE
Integrate NDM with SeaChest to fetch disk attributes. 

### ISSUE THREAD

**Issue by kmova** [openebs/node-disk-manager#143]
Refer:
- https://github.com/Seagate/openSeaChest
- https://www.snia.org/sites/default/files/SDC/2018/presentations/Storage_Resource_Mgmt/Ahmad_Muhammad_What%CE%93%C3%87%C3%96s_better_than_sg3utils_hd_sdparm.pdf

SeaChest exposes a c - library for reading / performing disk operations -- (better than s3gutils). Check how to integrated NDM (via c-go bindings) to access the inquiry data. Analyse if SeaChest can be a better option.

**Comment by richardelling** [comment]
IMHO, these (sg3_utils, smp_utils, and openSeaChest) are overkill. As part of the evaluation, 
consider that decoding the standard log and status pages might be simpler, easier, and less
interdependent than integrating with external projects.

**Comment by richardelling** [comment]
I agree with the approach. But keep in mind that the SMART stuff is dictated by standards
and changes very slowly. So the real question is whether it is worth creating a dependency
on others decoding pages, or just decode the pages directly and eliminate the dependency.
I don't know the answer, but having done this a few times now, the latter is very feasible and
likely simpler than the nuances of a c-go binding.

And yes, we'll need enclosures and expanders :-)

**Comment by akhilerm** [comment]
Done in #185
