### ISSUE TITLE
ndm should support dynamically attaching external disks to k8s nodes. 

### ISSUE THREAD

**Issue by kmova** [openebs/node-disk-manager#16]
Feature Request:

Example Usecase: Let us say Kubernetes Cluster is running in Amazon Cloud. As the Stateful workloads increase in number or there is an increase in data/capacity usage, **_ndm_** should provide an option to increase the storage available on the local nodes, triggering a provisioning of an EBS Disk and attaching to the Kubernetes node.

**Comment by umamukkara** [comment]
Now that CSI drivers are prevalent, to provision dynamic disks onto Kubernetes disks - we can use CSI driver of the external system. Some examples of interest are : 
- Cinder CSI driver
- OpenSDS storage dock

**Comment by muenchdo** [comment]
Is there a rough estimate on when this will be available?

**Comment by AmitKumarDas** [comment]
@muenchdo this is something that I have been currently working on. Its very alpha & is in my personal github i.e. https://github.com/AmitKumarDas/storage-provisioner

Do review and you can suggest on ways to integrate with auto scalers.

**Comment by akhilerm** [comment]
NDM will be used only for device discovery on the nodes.
