### ISSUE TITLE
Refactor code to send the SCSI CDB commands with highest supported version

### ISSUE THREAD

**Issue by kmova** [openebs/node-disk-manager#164]
The current code for determining capacity issues a CDB10 command and if there is a over-flow issues a CDB16 command. Instead, it would be good to have a mechanism to determine the highest version supported upfront and use that for subsequent commands.

**Comment by patheticpat** [comment]
I just pushed a PR (#174) addressing this issue.

**Comment by akhilerm** [comment]
Closing as the changes are no more required as per discussions in #174
