### ISSUE TITLE
ndm should be able to connect to iSCSI volumes from external storage

### ISSUE THREAD

**Issue by kmova** [openebs/node-disk-manager#17]
Feature Request:

Related to #16. In certain deployment scenarios, there could be already storage service available that expose volumes via iSCSI. _**ndm**_ should be able to connect to these remove iSCSI volumes and attach them to Kubernetes Nodes. These iSCSI disks can then be used for creating Storage Pools or hostDir volumes. 

As an extended usecase, in case of nodes that fail and can't be recovered, the iSCSI volumes can be mounted on a new Node and the Stateful workloads using them can be restarted.

**Comment by akhilerm** [comment]
NDM will detect only devices that are connected to the node, and wont be handling the actual connection of those devices.
