### ISSUE TITLE
ndm should be able to get the correct details of the node.

### ISSUE THREAD

**Issue by yudaykiran** [openebs/node-disk-manager#177]
**What happened**:
- When run on an EKS cluster, the hostname label obtained by NDM is different from the hostname label assigned to the node. This resulted in the pod staying in pending state as it could not get scheduled.  
**What you expected to happen**:
NDM should be able to get the correct node details.
**How to reproduce it (as minimally and precisely as possible)**:
- Create a cluster on EKS with Ubuntu as an AMI image.
- Apply openebs-operator.yaml.
- The cstor-sparse-pool pods of openebs will be in pending state.
**Anything else we need to know?**:
Logs Attached:
[kdd.txt](https://github.com/openebs/node-disk-manager/files/2609836/kdd.txt)
[kdn.txt](https://github.com/openebs/node-disk-manager/files/2609837/kdn.txt)
[kdp.txt](https://github.com/openebs/node-disk-manager/files/2609838/kdp.txt)

**Comment by akhilerm** [comment]
Fixed in #290
