### ISSUE TITLE
Custom Disks (not detected automatically) are not usable by openebs

### ISSUE THREAD

**Issue by segator** [openebs/node-disk-manager#189]
How Can I add non standar disks like  iscsi disks, or for example I want to add single partition to storagepoolclaim or zfs zvol /LVM
If I try to add manually the kind:disk object I got status inactive, any example?

**Comment by segator** [comment]
It works after delete openebs-ndm and destroyed custom disks, spc and sc and then redeployed.

**Comment by juwalter** [comment]
@segator - I am facing the same issue, but deleting and reinstalling openebs-ndm does not help me.

My setup is like so:

```zfs create -V 2000G -b $(getconf PAGESIZE) -o compression=lz4 -o com.sun:auto-snapshot=false rpool/openebs```  (fyi - my ZFS root pool is called "rpool", not "tank")

now, I would like openebs-ndm to recognise /dev/zd0 (or /dev/zvol/rpool/openebs) as a valid device

**Comment by umamukkara** [comment]
Just as a note, I am pasting some details below:

Below notes is applicable only if you are trying to setup a new zpool on fresh disks:
-----------------------------------------------------------------------------------

You don't need to setup and manage zpools and setup zvols for NDM. cStor and NDM does this for you

The baremetal disks are discovered and setup as disk custom disk resources (CRs) by NDM. You then create a config file (spc-config.yaml) and populate the disk CRs of each node into that and select the RAID type (RAID0 and RAID1) are supported now. Upon executing the kubectl apply -f command, OpenEBS  creates a cStorPool instance on each of the node that was specified in the spc-config.yaml with the disks specified on those nodes 

Next, you create StorageClasses pointing to that pool and create PVC/PV


Now, each created PV is internally a zvol on each of the cStorPool instance and cStor also replicates the data into the zvols (if replicaCount in StorageClass spec is 3)

**Comment by kmova** [comment]
custom disks can be added with an label called ndm.io/managed: "false"
https://github.com/openebs/node-disk-manager/pull/192
