### ISSUE TITLE
hack/build.sh fails latest version of shellcheck

### ISSUE THREAD

**Issue by michael-db** [openebs/node-disk-manager#191]
The shellcheck output gives the problem and the fix

    In ./hack/build.sh line 110:
    if [[ "${NDM_AGENT_DEV}" ]]; then
        ^----------------^ SC2244: Prefer explicit -n to check non-empty string (or use =/-ne to check boolean/integer).

    Did you mean:
    if [[ -n "${NDM_AGENT_DEV}" ]]; then

    For more information:
    https://www.shellcheck.net/wiki/SC2244

SC2244 was added just a few days ago to shellcheck.

Should the "latest" version of shellcheck continue to be used, or should the latest release be chosen manually? If the latter then the relevant line in the Makefile could be changed from
wget -c 'https://goo.gl/ZzKHFv' -O - | tar -xvJ -C /tmp/
to
wget -c 'https://storage.googleapis.com/shellcheck/shellcheck-v0.6.0.linux.x86_64.tar.xz' -O - | tar -xvJ -C /tmp/

**Comment by akhilerm** [comment]
Fixed in #193

**Comment by akhilerm** [comment]
Thanks @michael-db for reporting. Issue is fixed and merged to master.
