### ISSUE TITLE
NDM pod should be able to run in unprivileged mode

### ISSUE THREAD

**Issue by akhilerm** [openebs/node-disk-manager#203]
Currently, NDM Daemon set runs in the privileged mode. But we should be able to run the pod in unprivileged mode and get the same functionalities

**What is the expected behavior?**
NDM requires `privileged:true` when deploying as a daemon set for its proper working. NDM should be able to run without privileged access to the node, and work exactly in the same manner. A work around should be found out so that `/dev` and `/sys` directories from the host can be accessed in unprivileged mode, either using bind mount or some other mechanism like `LINUX_CAPS`

**Comment by akhilerm** [comment]
NDM requires privileged mode because it requires access to `/dev` and `/sys` directories for monitoring the devices attached and also to fetch the details of the attached device using various probes.

`LINUX_CAPS` in the docker engine allows to give a container only certain permissions which it require instead of the complete privilege. 
The permission bit mask of a container running in privileged mode is 
```
CapPrm:	0000003fffffffff
CapEff:	0000003fffffffff
```
which means it have all the privileges. Based on operations and access done by NDM, the CAPS were identified as `CAP_SYS_ADMIN`, `DAC_OVERRIDE`, `NET_ADMIN`.  But even if we give these capabilities to the container the device nodes are not created. Even when all the `LINUX_CAPS` are provided the device nodes are not created in the NDM container.

This is because, as per docker [documentation](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities) 

> When the operator executes docker run --privileged, Docker will enable access to all devices on the host as well as set some configuration in AppArmor or SELinux to allow the container nearly all the same access to the host as processes running outside containers on the host along with the capabilities


i.e privileged mode = All linux capabilites + removal of limitations enforced by cgroup device controller.

Therefore, to run the NDM pod in unprivileged mode, the configuration need to be set so that the cgroup /SELinux/AppArmor limitations can be bypassed.

>

**Comment by kmova** [comment]
Make sure the documentation is updated explaining why NDM requires privileged access.

**Comment by akhilerm** [comment]
Since NDM requires access to udev, procfs and sysfs of the host machine, NDM will have to be run in privileged mode.
