### ISSUE TITLE
Implement DeviceClaim, Device and Disk watcher/controller using operator-sdk

### ISSUE THREAD

**Issue by satbirchhikara** [openebs/node-disk-manager#205]
Implement DeviceClaim, Device and Disk watcher/controller using operator-sdk.

Task would include implementation of following functionality:
* DeviceClaim CRD and Watcher/Controller for DeviceClaim.
* Device CRD and Watcher/Controller for Device.
* Disk CRD and Watcher/Controller for Disk.

With these functionality, we are planing to have two binaries i.e. NDM daemon-set(Daemon-set) and NDM-operator(Deployment). What does it means is that Makefile, build script and docker push scripts also getting changed. With these changes, you have option to make ndm-daemon-set of ndm-operator.

* make ndo (for ndm-operator)
* make ndm (for ndm-daemonset)
* make (for both)

With these changes, we are going to implement device and device Claim CR. Also we are going to implement controller for disk, device and device Claim CR which would implement reconcile logic in it.

Apart from that node-disk-operator(ndo) would be responsible for checking liveness of nodes and based on status of node, it would mark disk Inactive.

**Comment by akhilerm** [comment]
Changes are merged in #218 and #245
