### ISSUE TITLE
Add `--bind-address` CLI option

### ISSUE THREAD

**Issue by vibornoff** [openebs/node-disk-manager#208]
Currently NDM accepts `--port` CLI option overriding default (:9090) listening port.

It would be handy to accept `--bind-address` option also to make NDM listenting on a desired address, not `0.0.0.0`/`::`.

**Comment by akhilerm** [comment]
@vibornoff  Thanks for raising the issue.  We will work on including `--bind-address` CLI option in NDM.

A patch for doing this is also welcome.

**Comment by aswathkk** [comment]
@akhilerm May I work on this?

**Comment by akhilerm** [comment]
@aswathkk  yes. you can take it up.

**Comment by akhilerm** [comment]
An issue #324  is raised to remove the unused flags.

**Comment by akhilerm** [comment]
NDM has a grpc endpoint which listens on 9115, and can be configured using `api-service-address` flag
