### ISSUE TITLE
Direct iSCSI support for SAN and NAS

### ISSUE THREAD

**Issue by joshuacox** [openebs/node-disk-manager#239]
It should bepossible for me to feed openebs the address for an iscsi target, and perhaps some chap creds, and have openEBS use that iscsi target directly.

If you are using FreeNAS it would look something like:

1. Add virtual disk to freeNAS
1. Add new disk to pool in --> http://myfreeNAS.host/ui/storage/pools
1. Add pool to extent in --> /ui/sharing/iscsi/extent
1. Add portal --> /ui/sharing/iscsi/portals/add
1. Define initiators (ALL for now) --> /ui/sharing/iscsi/initiator
1. Add target specifying portal from above --> /ui/sharing/iscsi/target
1. Finally add an associated target --> /ui/sharing/iscsi/associatedtarget

Now here is where I think a new feature must be implemented in OpenEBS, I want to give openEBS the target address/hostname/ip and some chap info.  At the moment you would do something like:

```
iscsiadm -m discovery -t sendtargets -p myfreeNAS.host 
iscsiadm -m node --login
```

However, this results in:

1. One iSCSI connection from the node to the freeNAS target to mount the resulting /dev/sdX block device directly onto that node
1. A second iSCSI connection from the container to that node as OpenEBS finds that there is a blank block device on that node and it gets used for one of the OpenEBS pools

What I want is a single iSCSI connection not two daisy chained to minimize latency etc.

This is request is the result of the conversation [here](https://github.com/openebs/openebs-docs/issues/572), and is an addition to #17

**Comment by joshuacox** [comment]
@kmova I thought I'd answer you here on what hardware.  For testing purposes I have some dell compellent, and IBM storage units.  

But I don't really expect OpenEBS to have to worry about the differences between those units.  All of my testing at the moment is using a VM with FreeNAS loaded onto it exposing an extent as detailed above.

**Comment by richardelling** [comment]
I see value for NDM monitoring iSCSI initiator health.

Since iSCSI initiators are already supported by k8s, is there anything preventing such a configuration today? Perhaps policy barriers? Policies can be changed...

**Comment by joshuacox** [comment]
Just to be clear you can manually set up an iscsi volume for k8s as described [here](https://github.com/kubernetes/examples/tree/master/staging/volumes/iscsi). 

And I am very pleased with the performance and flexibility that jiva and cstor provide.

But when it comes to production I'd like to offer something as close to the experience of Amazon EBS as possible (which is also just a wrapper around iSCSI and the AWS SAN as I understand it).  And on a big production grade cluster I'd like to separate out the storage as much as possible from the nodes and mirror what AWS does.

**Comment by akhilerm** [comment]
@kmova How should we take this up?

**Comment by joshuacox** [comment]
I'm not even certain this is a good idea anymore.  Perhaps as a backup scenario.  But this goes a bit against what openEBS is doing in terms of scaling well horizontally as nodes are added to the system (that have open block storage).  For example, in a given scenario say an elastic search cluster, if they are all hammering the same SAN that SAN becomes the bottleneck and sort of works against any 'clustering'.  That being said, I do have some big hardware SANs I'd like to consume, so perhaps snapshots or some other form of backup directly to such a SAN would be useful.  Also, of note is that I am also moving away from cstor entirely in favor of the performance of localPV.  Feel free to close this issue, as I have long since worked around it.  But I am happy to be included in any discussion that might give a backup solution over  iscsi to a specific target, or provide any input and even testing with any given hardware I have available, and I'd even work towards submitting a PR on maybe a backup solution with a given iscsi target.

**Comment by akhilerm** [comment]
The requirement is no longer valid and not in the current roadmap.
