### ISSUE TITLE
Partition information of Virtual_disk is not getting filled

### ISSUE THREAD

**Issue by akhilerm** [openebs/node-disk-manager#243]
**What happened**:
Partition information of `Virtual_disk` attached to node is not getting populated into the Disk resource.

**What you expected to happen**:
Partition type and filesystem type of partitions on the disk should be available inside the Disk resource.

**How to reproduce it (as minimally and precisely as possible)**:
Attach a `Virtual_disk` having partitions onto a node, the disk CR for the disk will be created, but the corresponding partition data will not present in the disk CR.

**Anything else we need to know?**:
Setup:
SUSE CaaS platform, Kubic:MicroOS
VMWare Virtual Disk having 2 partitions
```
sdb      8:16   0   50G  0 disk 
├─sdb1   8:17   0   50G  0 part 
└─sdb9   8:25   0    8M  0 part
```

**Comment by harshthakur9030** [comment]
This issue is fixed by https://github.com/openebs/node-disk-manager/pull/386 .

**Comment by akhilerm** [comment]
Closing this issue as the disk resource has been deprecated in #326 , #427  and blockdevice resource now supports partitions.
