### ISSUE TITLE
Inactive disk CRs observed in CI cluster

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/node-disk-manager#249]
**What happened**:
- Deployed Openebs operator 0.9.x and ndm as v0.3.5 in 5 node cluster.
- Each node have one disk attached.
- Initially, it showed 5 disks 
kubectl get disks 
```
disk-19e671b7c0078253d79a13b74c2b5cf8     40m
disk-5eff6e58ae82c9b2e81811cc728df4f0     40m
disk-67e9022ac51b7b598b8184445dccbbf5     40m
disk-70906132b38092d865c6b5c2ba06dc05     40m
disk-b9bf60454319b9e5524f366499784ed0     40m
```
- After running some functional test, the number of disk CRs increased. Several disk were seen to be in inactive state. 

```
disk-12e2abc1f2ad55ca478d39c2e58c44fd     3m
disk-19e671b7c0078253d79a13b74c2b5cf8     40m
disk-5eff6e58ae82c9b2e81811cc728df4f0     40m
disk-67e9022ac51b7b598b8184445dccbbf5     40m
disk-69b95d266d8dfb57429fed3304edebd4     11m
disk-70906132b38092d865c6b5c2ba06dc05     40m
disk-a9e54bc9bf8e5f3e2b6532682ea333bf     26m
disk-b9bf60454319b9e5524f366499784ed0     40m
```
It is to be noted that no chaos has been injected into disk/ndm specific components.

**What you expected to happen**:
- Inactive(stale) should not be present.

**Anything else we need to know?**:
- Disks describe log
[ndm-describe-disks.log](https://github.com/openebs/node-disk-manager/files/3165574/ndm-describe-disks.log)
- ndm pod logs 
[ndm-log-node1.log](https://github.com/openebs/node-disk-manager/files/3165577/ndm-log-node1.log)
[ndm-log-node3.log](https://github.com/openebs/node-disk-manager/files/3165578/ndm-log-node3.log)

**Comment by akhilerm** [comment]
Closing as disk resources are deprecated / removed in favour of blockdevice resources.
