### ISSUE TITLE
Write test cases for mount-probe

### ISSUE THREAD

**Issue by akhilerm** [openebs/node-disk-manager#253]
Mount-probe is a new probe introduced to fetch mount related information(mountpoint, filesystem) of block devices that has been attached to the node. 

Test cases need to be written for `FillDiskDetails` in mount-probe.

**Comment by avats-dev** [comment]
@akhilerm I can try this one too. What do you think?

**Comment by akhilerm** [comment]
Sure @avats-dev , you can work on it. Thanks for taking it up.

**Comment by akhilerm** [comment]
[This](https://github.com/openebs/node-disk-manager/blob/master/cmd/ndm_daemonset/probe/mountprobe.go) is the file for which you want to write the test. You can check out other test files in the same package to see, how tests are structured and how they are written in golang.

**Comment by akhilerm** [comment]
@avats-dev , If you have any doubts regarding the tests or implementation, you can raise your queries in the [`#openebs-dev`](https://kubernetes.slack.com/messages/openebs/) channel in [kubernetes slack workspace](https://openebs.io/community).

**Comment by akhilerm** [comment]
@avats-dev Are there any updates on this issue?

**Comment by akhilerm** [comment]
@avats-dev Will you be able to work on this issue. Else, I can unassign and free up the issue for others to take up.

**Comment by Z0Marlin** [comment]
@akhilerm anyone working on this issue? I can take this up

**Comment by akhilerm** [comment]
Sure @Z0Marlin . I will assign to you.
