### ISSUE TITLE
Fetch disk attributes from underlying disks and save them on disk objects

### ISSUE THREAD

**Issue by kmova** [openebs/node-disk-manager#27]
The initial implementation of the disk objects in #25, is fetching the following information:
- capacity
- serial number
- model 
- vendor 

The above details are fetched via lsblk command. 

But there are several other attributes that need to be obtained (originally discussed as part of https://github.com/openebs/openebs/issues/545)

Static Attributes:
* physical location (ie enclosure slot number)
* rotational speed (if hard disk)
* sector size
* write cache
* FW revision level

Some of the Dynamic Attributes (#28) will be added as well for easy retrieval. 
* state (online, removed, etc)
* status (normal, faulted)

**Comment by gila** [comment]
If we use a generic interface (e.g SGIO) you can do all the above and ditch lsblk or any external binary as the SGIO interface is a raw ioctl interface which maps nicely to golang.

**Comment by akhilerm** [comment]
Done in #185 and #58
