### ISSUE TITLE
Core dumps are getting written to `/var/openebs/sparse` for all programs on the system

### ISSUE THREAD

**Issue by akhilerm** [openebs/node-disk-manager#279]
**What happened**:
Used the default `ndm-operator.yaml` to deploy Node-Disk-Manger. The core dumps for crashes of NDM are getting written to `/var/openebs/sparse`. The core dumps for all programs that are running on the node is also getting written into the same directory.

**What you expected to happen**:
Only core dumps for crashes happening to NDM binary should be written to `/var/openebs/sparse`. Also, the core dump location should be made configurable

**How to reproduce it (as minimally and precisely as possible)**:
1. Install `openebs-ndm` using the default `operator.yaml` file. 
2. SSH into the node running the NDM daemonset.
3. `kill -11 <pid>` to any running process on the node. This will cause the core to be dumped and the dump will be saved to `/var/openebs/sparse`

**Comment by grzechukol** [comment]
I can confirm that I've encountered this error. Is there any plan to fix this issue? Seen on OpenEBS NDM v0.4.2.

**Comment by akhilerm** [comment]
The kernel does not support per-container core patterns yet.. There is a [patch](https://lore.kernel.org/patchwork/patch/643798/) in linux kernel for making the `core_pattern` support namespaces. 
Per container core_pattern is required so that NDM can dump the core files to a specified location without changing the settings on the host machine

**Comment by akhilerm** [comment]
Fixed in #358
