### ISSUE TITLE
Add disk status related metrics fetched via SCSI commands

### ISSUE THREAD

**Issue by kmova** [openebs/node-disk-manager#28]
There are some dynamic status parameters that determine the health of the underlying disks like:
- status (faulted, normal)
- temperator
- fan speed
- crc errors
- medium errors

This tasks involves investigating the the details that need to be monitored and added them as metrics to prometheus.

**Comment by akhilerm** [comment]
openSeachest is currently used to get this data and expose them as prometheus metrics.
