### ISSUE TITLE
Support disk usage metrics in node-disk-manager

### ISSUE THREAD

**Issue by kmova** [openebs/node-disk-manager#29]
The following metrics should be available to be seen per disk object in prometheus:

- Reads
- Writes
- Read Size
- Write Size
- Read Latency
- Write Latency
- Average Read Block Size
- Average Write Block Size

Also, need to look at tools like "iostat" for a reference of parameters that can be exported.

**Comment by ShovanMaity** [comment]
1. [Node-exporter](https://github.com/prometheus/node_exporter) read system file like `/proc/diskstats` this file contains some information of disk.
```
8       0 sda 28987 5911 2163548 1947012 11137 17181 699690 269512 0 182512 2216872
8       1 sda1 46 0 4424 2028 0 0 0 0 0 1912 2028
8       2 sda2 128 496 12338 4068 2 0 2 0 0 3192 4068
8       3 sda3 40 0 4128 2896 0 0 0 0 0 2008 2896
8       4 sda4 28613 5415 2130018 1931732 10637 17181 699688 254348 0 170792 2188892
8       5 sda5 40 0 4128 2860 0 0 0 0 0 2636 2860
8       6 sda6 42 0 4144 2776 0 0 0 0 0 2688 2776  
11       0 sr0 0 0 0 0 0 0 0 0 0 0 0 
179       0 mmcblk0 137 183 8619 360 0 0 0 0 0 160 360
179       1 mmcblk0p1 110 183 6515 284 0 0 0 0 0 120 284
8       6 sda6 42 0 4144 2776 0 0 0 0 0 2688 2776
11       0 sr0 0 0 0 0 0 0 0 0 0 0 0 
179       0 mmcblk0 137 183 8619 360 0 0 0 0 0 160 360
179       1 mmcblk0p1 110 183 6515 284 0 0 0 0 0 120 284  
```
We can generate metrics of iostat from there. More info about content of that file [link1](https://www.kernel.org/doc/Documentation/iostats.txt) ,[link2](https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats)
Node exporter have different collector we have to take diskstats collector only. 
[1. collector.go](https://github.com/prometheus/node_exporter/blob/master/collector/collector.go), [2. paths.go](https://github.com/prometheus/node_exporter/blob/master/collector/paths.go), [3. diskstats_linux.go](https://github.com/prometheus/node_exporter/blob/master/collector/diskstats_linux.go)

**Comment by ShovanMaity** [comment]
2. [Cadviser](https://github.com/google/cadvisor) It expose stats at /metrics endpoint but there is no partition level stats. If there is one disk named sda with multiple partition (sda1,sda2,sda3...) It will show only stat of sda

**Comment by kmova** [comment]
Is there any overlap with kube-state-metrics?

**Comment by ShovanMaity** [comment]
Implementation details : 
`/proc/diskstats` file provide us with details of disks 
`8       0 sda 28987 5911 2163548 1947012 11137 17181 699690 269512 0 182512 2216872`
this is content of a single line of `/proc/diskstats` file.
 ```
Field 1 - #major number
 Field 2 - #minor mumber
 Field 3 - #device name
 Field 4 - #reads completed successfully
 Field 5 - #reads merged
 Field 6 - #sectors read
 Field 7 - #time spent reading (ms)
 Field 8 - #writes completed
 Field 9 - #writes merged
Field 10 - #sectors written
Field 11 - #time spent writing (ms)
Field 12 - #I/Os currently in progress
Field 13 - #time spent doing I/Os (ms)
Field14 - #weighted time spent doing I/Os (ms)
```

For Read and Write Latency
```
(Current time spent reading/writing - Previous time spent reading/writing) /
(Current writes/reads completed successfully - Previous writes/reads completed successfully)
```
For Average Read/Write Block Size
```
(Current sectors read/write- Previous sectors read/write) /
(Current writes/reads completed successfully - Previous writes/reads completed successfully) * 
sectorssize
```

**Comment by ShovanMaity** [comment]
Currently this issue related PR is blocked on integration testting. Functionality and Unit test case are there in pr (#34)

**Comment by akhilerm** [comment]
Disk usage metrics are collected using seachest and exposed as prometheus metrics using the ndm-exporter
