### ISSUE TITLE
Move from minikube to kubeadm for integration-test

### ISSUE THREAD

**Issue by akhilerm** [openebs/node-disk-manager#314]
Currently node-disk-manager uses minikube for running integration tests. But while going for cross-platform support, minikube cannot be used for testing. Therefore, the testing needs to be moved from minikube to `kubeadm` based local cluster.

The changes need to be made in [.travis.yml](https://github.com/openebs/node-disk-manager/blob/ebc261b38dc3821663de2175ae48cc94d567f026/.travis.yml#L30). Setting up and starting of minikube,  should be replaced and a cluster using `kubeadm` should be brought up

**Comment by RanadeepPolavarapu** [comment]
I can tackle this.

**Comment by rahulchheda** [comment]
Why not use KIND?

**Comment by akhilerm** [comment]
In the integration tests, we are using some disk attach/detach cases by creating a loop device. Need to try out if it works on KIND,

**Comment by akhilerm** [comment]
All the builds and tests has been migrated to github actions and multiarch images are created now. Therefore, moving to kubeadm based cluster is no longer required.
