### ISSUE TITLE
remove unused cobra flags from NDM daemon

### ISSUE THREAD

**Issue by akhilerm** [openebs/node-disk-manager#324]
NDM Daemon uses cobra for the CLI interface. There are certain flags like, `metricspath`, `port` and `kubeconfig` which are no longer required to be used with NDM daemon. These flags need to be removed and new flag `-v` need to be introduced so that verbosity can be added to log messages.

**What is the expected behavior?**
Only the flags that are required by NDM daemon should be made availbale via the CLI.

**Comment by NaveenBellary** [comment]
@akhilerm, I'd like to take this up as part of hacktoberfest
