### ISSUE TITLE
Add arm builds and create a multi-arch docker image manifest

### ISSUE THREAD

**Issue by joekhoobyar** [openebs/node-disk-manager#379]
I would like to be able to run `openebs/node-disk-operator` on a mixed-arch kubernetes cluster, where I have a few `amd64` and a few `armv7l` architectures.

To do this, it would be great to have a multi-arch docker image to utilize.

Currently, the only image I can access is `quay.io/openebs/node-disk-operator-amd64:v0.4.7`.

I would like to be able to pull `quay.io/openebs/node-disk-operator:v0.4.7` and have it be a manifest list that references all of the supported arches.

How close are we to being able to do this?  Is `arm` support still in alpha?

**Comment by akhilerm** [comment]
Currently, we have `arm64` docker images available only for the `ci` tag, which has lot of changes from the `v0.4.x` releases. 
We will raise a PR to add `arm64` docker images for the `v0.4.x` releases and try to include it in `v0.4.8` release.

`node-disk-manager` (NDM) now has support for `arm64` ,`amd64` and `ppc64le` architectures. But, for some other components in `openebs`, auto-building `arm` based docker images is still a work in progress. If you want to use the NDM only, I think multiarch will be possible from next release.

I have another question on the architectures that you have mentioned. Is `armv71` different from `arm64`? We have enabled builds only for `arm64`, so if it is different may need to explore on it.

**Comment by akhilerm** [comment]
PR #380 adds `arm64` auto-build to `v0.4.x` release branch

**Comment by akhilerm** [comment]
The PR has been merged. Docker images will be pushed for `arm64` from `v0.4.8`

**Comment by joekhoobyar** [comment]
@akhilerm, yes `armv7l` is a 32-bit arm architecture.  It corresponds to the `arm` arch target in golang.

Many boards are 32-bit arm, such as: ODroid XU4, Raspberry PI 2 v1.1 or earlier

**Comment by kmova** [comment]
Hi @joekhoobyar - would you like to contribute towards moving towards a Docker manifest  `quay.io/openebs/node-disk-operator` than can help with pulling different architecture images. Today we have support for amd64,  arm64 and power. If we have a setup in circle ci or github actions that can be used for building `arm7l`, we would love to automate it. 

Would love to hear your suggestions?

**Comment by joekhoobyar** [comment]
I would love to contribute, sure.  I'm sure I have all of the local capabilities to build `amd64` and `arm` arches without needing to run VM(s) and if need be, I could run software virtualized VM(s) to build `arm64` arches.

What do I need to do to get started with you guys?
- What standards should I be following?
- How do you prefer to orchestrate your docker image builds?  Shell scripts driving docker commands that consume Dockerfile(s)?
- What existing scripts for building docker image should I pick up and start modifying?

**Comment by joekhoobyar** [comment]
@kmova  - Did you see my above questions?

In the meantime, I will just pull the code down and play with the build, then make a fork.

**Comment by joekhoobyar** [comment]
@kmova  - On this [branch](https://github.com/joekhoobyar/node-disk-manager/tree/arm32) I am able to successfully build the *arm* binaries using a cross-compiler.

I will move on to the testing the docker image soon, but I am about to go on a weekend trip tomorrow morning, so I need to go pack.  :)

**Comment by akhilerm** [comment]
@joekhoobyar  Is it possible to use [buildx](https://docs.docker.com/buildx/working-with-buildx/) to create multi arch docker image and then create the docker manifest like `openebs/node-disk-manager:v0.4.8`?

> How do you prefer to orchestrate your docker image builds? Shell scripts driving docker commands that consume Dockerfile(s)?

Currently we are using a combination of Makefile, shell scripts and docker files to create the image. I prefer following a similar pattern for creating the manifest also.

> What existing scripts for building docker image should I pick up and start modifying?

you could refer [this](https://github.com/openebs/node-disk-manager/blob/master/Makefile)
