### ISSUE TITLE
how is ndm different from kubernetes dynamic storage provisioners e.g. GPD based provisioner

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/node-disk-manager#39]
I would like to know the difference between ndm & dynamic storage provisioner like `kubernetes.io/gce-pd` Is ndm not required if I use `kubernetes.io/gce-pd`

**Comment by harshthakur9030** [comment]
@AmitKumarDas , can you please explain how NDM fits with external provisioners? Noticed your work here: https://github.com/AmitKumarDas/storage-provisioner . Right now, in the provisioner property, we supply one by openebs which picks from storage pools, etc. How would it differ using this?

**Comment by AmitKumarDas** [comment]
https://github.com/mayadata-io/storage-provisioner is the current repo.
This can interact with any CSI drivers to provision storage (read GPD, EBS, etc), attach them to nodes & hence make them discoverable via NDM.

**Comment by akhilerm** [comment]
NDM does not handle provisioning, it just manages the disk discovery,  so that higher level operators can make use of it as explained [here](https://github.com/openebs/node-disk-manager#readme)
