### ISSUE TITLE
Node Disk Manager integration with Node Problem Detector for disks problems monitoring

### ISSUE THREAD

**Issue by shovanmaity** [openebs/node-disk-manager#42]
Design document of NDM integration with NPD for disks problems like disk attach or detach etc.

**Comment by ShovanMaity** [comment]
You can find initial design document [here](https://docs.google.com/document/d/1oaaKGT4SW9RfaR4ze_TiIyIGhmPILF7iH9-wRmiSc-A) feel free to suggest changes.

**Comment by akhilerm** [comment]
NDM currently exposes the metrics that can be used along with metrics from NPD. Both these metrics together can be used for problem monitoring with help from dashboards like grafana.
