### ISSUE TITLE
Make Disable lazy initialisation and enable DISCARD commands

### ISSUE THREAD

**Issue by xtaraim** [openebs/node-disk-manager#46]
Disable lazy initialization and enable DISCARD during format by passing the following parameters to mkfs.ext4:

-E lazy_itable_init=0,lazy_journal_init=0,discard
The lazy_journal_init=0 parameter does not work on instances with CentOS 6 or RHEL 6 images. For those instances, format persistent disks without that parameter.

-E lazy_itable_init=0,discard
Enable DISCARD commands on mount, pass the following flag to the mount command:

-o discard
Persistent disks work

**Comment by akhilerm** [comment]
Closing as NDM does not create filesystem on the disk and is out of scope of NDM.
