### ISSUE TITLE
Use epoll method instead of select calls for reading from file descriptor.

### ISSUE THREAD

**Issue by shovanmaity** [openebs/node-disk-manager#50]
We may miss a disk attach event when disk is attached after `pushDiskResources()` in the main thread and before `MonitorEvent()` calls select for the netlink fd in go routine. We should use `epoll` where after `epoll_create` and `epoll_ctl`, we can notify main thread that it is now listening for the `netlink fd` and it can proceed with the `pushDiskResources()` in that way we will not miss any attach/detach event.

**Comment by akhilerm** [comment]
Closing since this could not be observed using select call.
