### ISSUE TITLE
NDM is crashing on fresh GKE cluster

### ISSUE THREAD

**Issue by harshthakur9030** [openebs/node-disk-manager#515]
**What steps did you take and what happened:**
I installed NDM on fresh GKE cluster. 
This issue is happening from 0.9.x 

**What did you expect to happen:**
NDM to function

**The output of the following commands will help us better understand what's going on**:
[Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.]

https://pastebin.com/X2BGnpYZ

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- OpenEBS version : 2.3
- Kubernetes version (use `kubectl version`): 
- Kubernetes installer & version: 1.17
- Cloud provider or hardware configuration: GKE
- Type of disks connected to the nodes (eg: Virtual Disks, GCE/EBS Volumes, Physical drives etc) : None 
- OS (e.g. from `/etc/os-release`): Container-Optimised OS

**Comment by akhilerm** [comment]
The panic is occuring when trying to parse the `/proc/cmdline` file. In GKE, the file contents is as follow:
```
BOOT_IMAGE=/syslinux/vmlinuz.A init=/usr/lib/systemd/systemd boot=local rootwait ro noresume noswap loglevel=7 noinitrd console=ttyS0 security=apparmor virtio_net.napi_tx=1 systemd.unified_cgroup_hierarchy=false systemd.legacy_systemd_cgroup_controller=false csm.disabled=0 csm.pipe.enabled=1 csm.config.enabled=1 dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 i915.modeset=1 cros_efi root=/dev/dm-0 "dm=1 vroot none ro 1,0 2539520 verity payload=PARTUUID=9046BA55-94F8-9045-BB19-3BD2AF8886B8 hashtree=PARTUUID=9046BA55-94F8-9045-BB19-3BD2AF8886B8 hashstart=2539520 alg=sha256 root_hexdigest=6ed56ab0562829e69580632bfeab9fb33c8fe3eb8b87c86c90f33c1a62bb1ed7 salt=078fe048e9a61cf88232534bd064514e471e7efcbb565e368ef2e54b27f7e857
```

and the root is defined at `root=/dev/dm-0`, which is different from the expected format causing a parse error. 
cc: @zlymeda , Do you have any ideas on this?

**Comment by zlymeda** [comment]
Hi @harshthakur9030 
Is the /dev/dm-0 real device? or is it a symlink?

can you provide an output for 
`ls -l /dev/ | grep dm-0`

thanks
