### ISSUE TITLE
NDM BlockDevice should support multiple mount points

### ISSUE THREAD

**Issue by z0marlin** [openebs/node-disk-manager#558]
Partitions can have multiple mount points in Linux. While the BlockDevice struct in NDM [supports this](https://github.com/openebs/node-disk-manager/blob/b77aa7f29cfb9043a56b02c71c3182920d8192ed/blockdevice/blockdevice.go#L256), the BlockDevice k8s API resource can only store a single mount point.

https://github.com/openebs/node-disk-manager/blob/e4f921ce4494fc02e71a07669d4a6804de86cb9a/pkg/apis/openebs/v1alpha1/blockdevice_types.go#L202 

The API resource definition should be updated to store an array of mount points similar to the `BlockDevice` struct in package blockdevice.

Tasks:
- [x] Update mount package to return all mount points from mounts file
- [ ] Update blockdevice CR to hold a list of mount points

**Comment by Z0Marlin** [comment]
@akhilerm is there any discussion required in this issue or should I go ahead with the patch?

**Comment by akhilerm** [comment]
@Z0Marlin It can be directly updated because that will require a change in the version of the resource. This is one change that we have planned while migrating blockdevice to v1 . Another issue which also falls in the same category is [this](https://github.com/openebs/openebs/issues/2837). 

You can make all the internal changes such that all the mountpoints get fetched using the mountprobe and stored in the internal blockdevice struct. Only while converting it to the blockdevice API resource, we will choose one mountpoint. This makes it easier after migration to fill in the details and also reduces the patch size.

**Comment by Z0Marlin** [comment]
I see. So we can't make changes to the crd yet. All right, I'll make changes in the mount package to return all mount points and then mount probe can only select the first one.

**Comment by RealHarshThakur** [comment]
@akhilerm  We could add a new field called `MountPoints` of type `[]string` which would store all the mount points. Adding new fields in the CRD without version change is fine as there's no best practice around this upstream too. All we have to do is ensure that the user has applied the CRD with the new field, this can be done via a preupgrade job too. WDYT?

**Comment by akhilerm** [comment]
yes @RealHarshThakur .Thats a valid point and we can do it. But in that case, the resource will be having 2 mountpoint fields, `Mountpoint string` and `Mountpoints []string`. Should check if its okay to do so . cc: @kmova If its fine, then we can include mountpoints and while migrating remove the other field.

@Z0Marlin , if we do as @RealHarshThakur mentioned then you can straightaway implement the multiple mount points to CRDs also.

**Comment by RealHarshThakur** [comment]
Yeah, that would be small inconvenience we'll face until we move to next API version but we can avoid confusing the end users by just populating the `Mountpoints` field and leaving the `Mountpoint` empty. Similar change in kubectl output as well . 
From implementation perspective, we can just stop using the `Mountpoint` field in the controllers.

**Comment by z0marlin** [comment]
@RealHarshThakur can we reopen this issue? It also includes updating the BD crd which isn't done yet.

**Comment by akhilerm** [comment]
Reopening as blockdevice custom resource needs to be updated with multiple mount points.

**Comment by akhilerm** [comment]
At this point, we are not seeing a use case for modifying the CRD to support multiple mount points.
