### ISSUE TITLE
TestUdevProbe fails with SIGSEGV in certain systems

### ISSUE THREAD

**Issue by z0marlin** [openebs/node-disk-manager#589]
[`TestUdevProbe`](https://github.com/openebs/node-disk-manager/blob/110066c2d6626ba26b55660b6e9a00294140b6be/cmd/ndm_daemonset/probe/udevprobe_test.go#L136) returns SIGSEGV after trying to create a GPT partition on a disk that is currently being used by the system.

Crash logs can be found in [this pastebin](https://pastebin.com/i9QNMdwG).

The issue seems to occur in cases when ndm isn't able to generate a uuid for the disk. The code for uuid generation can be found [here](https://github.com/openebs/node-disk-manager/blob/110066c2d6626ba26b55660b6e9a00294140b6be/cmd/ndm_daemonset/probe/uuid.go#L30). The failure in generating the uuid leads ndm to try creating a partition on the disk. This in turn fails since the device is busy and finally the test fails due to a nil pointer dereference on [this](https://github.com/openebs/node-disk-manager/blob/110066c2d6626ba26b55660b6e9a00294140b6be/cmd/ndm_daemonset/probe/udevprobe_test.go#L205) line.

**Environment**
- OS: Ubuntu 20.10 (Linux 5.8.0-50-generic, x86_64)
- Number of disks: 1 (with 4 partitions). **The disk does not have a wwn**.
- The machine is a VM running in VMWare Workstation.

**Comment by Z0Marlin** [comment]
@akhilerm

**Comment by z0marlin** [comment]
This issue seems to be related to skipping error checks in the tests in multiple places. Adding appropriate checks should mitigate the issue.

**Comment by akhilerm** [comment]
Is only adding error check required? Dont we need also need to look at tests and say why the error is happening?

**Comment by z0marlin** [comment]
In the `TestUdevProbe` case, it tries fetching the blockdevice using the API client. But the device couldn't be added in the first place because a uuid couldn't be generated. The error check is skipped and a nil pointer is dereferenced. The other tests that might fail also seem to have similar calls. I'll check once if the underlying reason is the same.

**Comment by z0marlin** [comment]
All right, I have narrowed down this issue to `TestUdevProbe` only. But I also find some other issues in the unit tests. They aren't related to this but need fixing. One such issue can be found in `TestSysFsDeviceGetHolders` in [syspath_test.go](https://github.com/openebs/node-disk-manager/blob/9d601918ec8c34f2fdc82e647c979eb232d7c61a/pkg/sysfs/syspath_test.go). This test passes the first time it is run, but fails on subsequent runs. It looks like it creates certain files in tmp dir and they aren't being cleaned up properly.

Shall submit a PR for all the issues encountered.
