### ISSUE TITLE
[proposal] use `DiskGUID` instead of `PartitionUUID`

### ISSUE THREAD

**Issue by cospotato** [openebs/node-disk-manager#621]
**Describe the problem/challenge you have**
The implementation of disk identification described in [oep(NDM 0001)](https://github.com/openebs/openebs/blob/master/contribute/design/1.x/ndm/20190705-ndm-disk-identification.md#disk-identification-using-gpt-partitions) will create a GPT partition spans the complete disk for identification. Which cause user cannot re-partition the disk.

**Describe the solution you'd like**
The GPT header has a parameter called `DiskGUID` at offset `0x38` (described in [wiki](https://en.wikipedia.org/wiki/GUID_Partition_Table) section `Partition table header (LBA 1)`). 

Can we just add GPT disk label, don't create partition then use the `DiskGUID` to generate the BD name?

The `DiskGUID` can get from udev probe parameter `ID_PART_TABLE_UUID`.

```console
[root@worker-0 ~]# udevadm info --name=/dev/sdd | grep ID_PART_TABLE
E: ID_PART_TABLE_TYPE=gpt
E: ID_PART_TABLE_UUID=123772e1-7d6f-4f89-af51-3c4eb2f19c5b
```

```console
[root@worker-0 ~]# fdisk -l /dev/sdd
Disk /dev/sdd: 931.5 GiB, 1000204886016 bytes, 1953525168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: 123772E1-7D6F-4F89-AF51-3C4EB2F19C5B
```

**Anything else you would like to add:**
Closed issue #620 show a tricky scenarios. The disk is a physical NVMe disk but the udev don't append ID_WWN to it. NDM will create a single partition for it.

**Environment:**
- OpenEBS version
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- Type of disks connected to the nodes (eg: Virtual Disks, GCE/EBS Volumes, Physical drives etc)
- OS (e.g. from `/etc/os-release`):

@akhilerm

**Comment by kmova** [comment]
@cospotato One of the reasons for creating a partition was - when the block device is provided to an application like cstor, it would reformat the entire disk, overwriting the uuid. 

how are you planning to use the NDM? we could enhance the following code to take a flag and allow for only creating the partition table:

> https://github.com/openebs/node-disk-manager/blob/master/cmd/ndm_daemonset/probe/addhandler.go#L120

**Comment by cospotato** [comment]
Hello @kmova ,

My use case was - i want to reformat the entire disk to specific layout (multi partitions). So how the CStor reformat the disk and keep the partition UUID never changed ?

**Comment by akhilerm** [comment]
@cospotato . If you reformat the disk and create multiple partitions yourself, NDM will detect each partition and create a resource for them. Does that solve your issue?

**Comment by cospotato** [comment]
> @cospotato . If you reformat the disk and create multiple partitions yourself, NDM will detect each partition and create a resource for them. Does that solve your issue?

hello @akhilerm . No. I prefer the NDM only record the origin device but don't care about the partitions change on that device. Like the behavior now -- if parent device recorded then ignore the sub-device.

**Comment by cospotato** [comment]
Hello @akhilerm ! I committed a patch at #635 . Would you please add some advice ?

**Comment by cospotato** [comment]
Hello @kmova ! I committed a patch at #635 to add a feature about this issue. Would you please add some advice ?
