### ISSUE TITLE
 make release for opensean blocked by common.h file not found

### ISSUE THREAD

**Issue by superleo** [openebs/node-disk-manager#640]
**What steps did you take and what happened:**
Try to build openSeaChest
```shell
cd openSeaChest/Make/gcc
make release
```
**What did you expect to happen:**
- Build succesfully and the library file created

**The output of the following commands will help us better understand what's going on**:
```shell
# make release
mkdir -p openseachest_exes
cc -Wall -c -std=gnu99 -O3 -I../../opensea-common/include -I../../opensea-transport/include -I../../opensea-transport/include/vendor -I../../include -I../../opensea-operations/include -DDISABLE_TCG_SUPPORT ../../utils/C/openSeaChest/openSeaChest_Erase.c -o ../../utils/C/openSeaChest/openSeaChest_Erase.o
../../utils/C/openSeaChest/openSeaChest_Erase.c:27:20: fatal error: common.h: No such file or directory
 #include "common.h"
                    ^
compilation terminated.
make: *** [../../utils/C/openSeaChest/openSeaChest_Erase.o] Error 1
[root@nhk8s-master gcc]# vim ../../utils/C/openSeaChest/openSeaChest_Erase.c

[1]+  Stopped                 vim ../../utils/C/openSeaChest/openSeaChest_Erase.c
```

**Environment:**
CentOS Linux release 7.9.2009 (Core)

**Comment by akhilerm** [comment]
@superleo Did you clone the submodules also for openseachest? Ref [here](https://github.com/openebs/node-disk-manager/blob/master/build/install-dep.sh#L29)

**Comment by superleo** [comment]
@akhilerm thank you akhilerm, I missed the submodule. And resolved by `git submodule update --init --recursive`
