### ISSUE TITLE
Enhance feature gate package to add support for dependent feature gates

### ISSUE THREAD

**Issue by akhilerm** [openebs/node-disk-manager#651]
**Describe the problem/challenge you have**
The current [feature](https://github.com/openebs/node-disk-manager/tree/develop/pkg/features) supports adding features, and setting the default value of features. But there can be cases like one feature can be dependent on another. This functionality should also be included. 

for example:
if A is dependent on B, and B is set to False, then A should default to the default value.  

**Describe the solution you'd like**
A new `dependentFeature` variable should be made of type `map[Feature][]Feature`, so each feature can be dependent on multiple features. Then while [parsing](https://github.com/openebs/node-disk-manager/blob/develop/pkg/features/features.go#L126) the features, the new checks should be performed and if dependencies are not met, the feature should fall back to the default value.

**UseCase:**
A new feature `UsePartTableUUID` is being introduced which is dependent on `GPTBasedUUID`. So the package should make sure that `UsePartTableUUID` can be enabled only if `GPTBasedUUID` is also enabled.

**Comment by jdkramhoft** [comment]
I'd like to work on this
Should I simply enable support and add test cases, or should I also add UsePartTableUUID as a default supported feature string with GPTBasedUUID as a dependency?

**Comment by akhilerm** [comment]
Thanks @jdkramhoft .

Enabling support and adding test cases should be enough as the `UsePartTableUUID` changes are not yet merged.
