### ISSUE TITLE
Some devices do not have ID_WWN ID_VENDOR and resulting in duplicate uuid generated 

### ISSUE THREAD

**Issue by liuminjian** [openebs/node-disk-manager#656]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and the sequence of operations performed / commands you ran.]

i have some ssd devices which do not have ID_WWN ID_VENDOR property. so this device will generate the same uuid.
how to fix this problem.

![image](https://user-images.githubusercontent.com/7840869/143985231-49919eda-7c1a-439f-9a38-b502328a7ceb.png)

node-disk-manager 0.7

**What did you expect to happen:**

**The output of the following commands will help us better understand what's going on**:
[Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.]

* `kubectl get pods -n openebs`
* `kubectl get blockdevices -n openebs -o yaml`
* `kubectl get blockdeviceclaims -n openebs -o yaml`
* `kubectl logs <ndm daemon pod name> -n openebs`
* `lsblk` from nodes where ndm daemonset is running 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- OpenEBS version
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- Type of disks connected to the nodes (eg: Virtual Disks, GCE/EBS Volumes, Physical drives etc)
- OS (e.g. from `/etc/os-release`):

**Comment by akhilerm** [comment]
@liuminjian Can you also provide the feature flags that you are passing to NDM, along with NDM pod logs from the node where this issue is happening.

**Comment by liuminjian** [comment]
i did not pass feature-gates to ndm. The log content is as follows.

![image](https://user-images.githubusercontent.com/7840869/143988333-b0034778-c03d-4106-85fc-e4f258c1bd02.png)

i have a disk sdi on node 1 and sdf on node 2. the disk uuid is generated by ID_WWN ID_VENDOR ID_MODEL ID_SERIAL_SHORT.  but sdi and sdf does not have ID_WWN ID_VENDOR . so they get the same uuid.

**Comment by akhilerm** [comment]
NDM by default uses the feature gate `GPTBasedUUID`. If it is enabled, then this issue should not occur. NDM will go ahead and create partitions if the WWN is empty.


Can you share the initial log section, where it shows the feature gates that are active on the NDM daemon.

**Comment by Icedroid** [comment]
Our two k8s node 192.168.189.62 and 192.168.189.75 disk /dev/sdi on  192.168.189.62 and /dev/sdf on 192.168.189.75 has same ID_MODEL And  ID_SERIAL. So BD uuid is same. NDM found only one BD.

Node 192.168.189.62:
`# udevadm info --query=all --name=/dev/sdi|grep -wE 'ID_WWN|ID_VENDOR|ID_MODEL|ID_SERIAL`
>E: ID_MODEL=Samsung_SSD_860_EVO_1TB
E: ID_SERIAL=Samsung_SSD_860_EVO_1TB_2105T1128A000124

Node 192.168.189.75:
`# udevadm info --query=all --name=/dev/sdf|grep -wE 'ID_WWN|ID_VENDOR|ID_MODEL|ID_SERIAL`
>E: ID_MODEL=Samsung_SSD_860_EVO_1TB
E: ID_SERIAL=Samsung_SSD_860_EVO_1TB_2105T1128A000124


The NDM pod in node 192.168.189.62  log as  follow:
>I1130 03:08:39.079170       8 eventhandler.go:68] Processed details for /dev/sdi
I1130 03:08:39.079214       8 blockdevicestore.go:274] device: /dev/sdi is in use, updating only relevant fields
I1130 03:08:39.181022       8 request.go:530] Throttling request took 101.74844ms, request: PUT:https://10.96.0.1:443/apis/openebs.io/v1alpha1/namespaces/openebs/blockdevices/blockdevice-7a366d9a9e4dc7b5b49d21a1a7769172

NDM update the bd of 192.168.189.62 actually is in 75 node.
`kubectl get bd blockdevice-7a366d9a9e4dc7b5b49d21a1a7769172 -n openebs -o yaml`
```spec:
  capacity:
    logicalSectorSize: 512
    physicalSectorSize: 512
    storage: 1000204886016
  claimRef:
    apiVersion: openebs.io/v1alpha1
    kind: BlockDeviceClaim
    name: bdc-pvc-b4d5b06a-5422-4662-ba90-c1b39341ca2f
    namespace: openebs
    resourceVersion: "357160761"
    uid: 66828c74-1f88-443e-b686-d5b4ad631ee8
  details:
    compliance: SPC-4
    deviceType: disk
    driveType: SSD
    firmwareRevision: 'XKR '
    hardwareSectorSize: 512
    logicalBlockSize: 512
    model: Samsung_SSD_860_EVO_1TB
    physicalBlockSize: 512
    serial: 2105T1128A000124
    vendor: ""
  devlinks:
  - kind: by-id
    links:
    - /dev/disk/by-id/ata-Samsung_SSD_860_EVO_1TB_2105T1128A000124
  - kind: by-path
    links:
    - /dev/disk/by-path/pci-0000:84:00.0-sas-0x56c92bf0002a4eec-lun-0
    - /dev/disk/by-path/pci-0000:84:00.0-sas-exp0x56c92bf0002a4eff-phy12-lun-0
  filesystem: {}
  nodeAttributes:
    nodeName: 192.168.189.75
  partitioned: "No"
  path: /dev/sdf
status:
  claimState: Claimed
  state: Active
```

**Comment by akhilerm** [comment]
@Icedroid Can you check if the `GPTBasedUUID` feature is set to enable?

**Comment by Icedroid** [comment]
@akhilerm The GPTBasedUUID feature didn't match this issue. We use one rawdisk for one bd. Don't want one gpt part as a bd.

**Comment by akhilerm** [comment]
`GPTBasedUUID` was introduced to solve this exact use case, where a disk does not have any uniquely identifiable information (like WWN).  

I guess your use case is, the disks does not have any uniquely identifiable information, but you still want to use the disk as a whole without needing any GPT partitions on it.

**Comment by Icedroid** [comment]
Right. We want to use the disk as a whole without needing any GPT partitions on it.  Must open GPTBasedUUID feature? The feature let NDM auto parted my raw disk add a gpt partition, then bd link to the gpt partition?

**Comment by Icedroid** [comment]
Now our ndm init start log:
```
[entrypoint.sh] launching ndm process.
I1130 03:08:38.302987       8 commands.go:72] Starting Node Device Manager Daemon...
I1130 03:08:38.303041       8 commands.go:73] Version Tag : ci
I1130 03:08:38.303062       8 features.go:84] No feature gates are set
I1130 03:08:38.510699       8 controller.go:251] BlockDevice CRD is available
I1130 03:08:38.515418       8 filter.go:60] registering filters
I1130 03:08:38.515443       8 filter.go:68] configured os disk exclude filter : state enable
I1130 03:08:38.515769       8 filter.go:68] configured vendor filter : state enable
I1130 03:08:38.515787       8 filter.go:68] configured path filter : state enable
I1130 03:08:38.515795       8 filter.go:68] configured device validity filter : state enable
I1130 03:08:38.515802       8 probe.go:64] registering probes
I1130 03:08:38.515832       8 probe.go:85] configured seachest probe : state disable
I1130 03:08:38.515857       8 probe.go:85] configured smart probe : state enable
I1130 03:08:38.515867       8 probe.go:85] configured mount probe : state enable
I1130 03:08:38.515968       8 probe.go:85] configured udev probe : state enable
I1130 03:08:38.516009       8 udevprobe.go:251] starting udev probe listener
```

**Comment by akhilerm** [comment]
> Must open GPTBasedUUID feature? 

yes you should enable it. Or in latest version of NDM, the feature is enabled by default.


> The feature let NDM auto parted my raw disk add a gpt partition, then bd link to the gpt partition?

Yes, One single partition will be created that spans the entire disk, and the BD will be created for this partition.

**Comment by Icedroid** [comment]
Because our production enviroment many BD has been Claimed. If now open GPTBasedUUID feature, the old BD name will regenerate? will it affect the running of vm or pod which mounted old bd?

**Comment by akhilerm** [comment]
@Icedroid Are there any updates on this issue?

**Comment by Icedroid** [comment]
@akhilerm no. Thanks. You can close the issus.

**Comment by akhilerm** [comment]
Were you able to migrate to using the GPTBasedUUID?

**Comment by Icedroid** [comment]
We  only use bd to be  raw disk in a virtual machine. So we can't use GPTBasedUUID feature.  In this situation we change to this:
https://github.com/EdgeCloudX/node-disk-manager/pull/3
> Were you able to migrate to using the GPTBasedUUID?

**Comment by akhilerm** [comment]
Ok . I think I understand the issue solved in the EdgeCloud fork. But I have a doubt: What will happen if you want to move a disk that is already in use (with no WWN) to another node in the same cluster?

**Comment by Icedroid** [comment]
> Ok . I think I understand the issue solved in the EdgeCloud fork. But I have a doubt: What will happen if you want to move a disk that is already in use (with no WWN) to another node in the same cluster?

If the disk is mounted by a kubevirt vm, can't be moved to another. So the disk move to another node, we hope to regenerate a new bd.

**Comment by akhilerm** [comment]
ok. in that case its good. Thanks @Icedroid
