### ISSUE TITLE
NDM pods goes to 'CrashLoopBackOff' state on CentOS based k8s cluster.

### ISSUE THREAD

**Issue by dargasudarshan** [openebs/node-disk-manager#69]
NDM pods goes to 'CrashLoopBackOff' state on CentOS based k8s cluster.

```
[vagrant@kubemaster-01 k8s]$ kubectl get pods -n openebs
NAME                                         READY     STATUS             RESTARTS   AGE
maya-apiserver-75fbc44d89-lnz4q              1/1       Running            0          17m
node-disk-manager-gv9m5                      0/1       CrashLoopBackOff   6          17m
node-disk-manager-q29n7                      0/1       CrashLoopBackOff   7          17m
node-disk-manager-v9gnl                      0/1       CrashLoopBackOff   7          17m
openebs-provisioner-7777f787fb-x9nwf         1/1       Running            0          17m
openebs-snapshot-operator-74f88657f4-zq8tj   2/2       Running            0          17m
```
NDM pod logs:
 ```
kubectl logs node-disk-manager-gv9m5 -n openebs -p
container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/proc/1/mounts\\\" to rootfs \\\"/var/lib/docker/overlay/f4ad3e1e27cd208a461450a1f577826bf4a519566d612fbc583da2187a540c20/merged\\\" at \\\"/var/lib/docker/overlay/f4ad3e1e27cd208a461450a1f577826bf4a519566d612fbc583da2187a540c20/merged/host/mounts\\\" caused \\\"permission denied\\\"\""
```
```
Events:
  Type     Reason                 Age               From                    Message
  ----     ------                 ----              ----                    -------
  Normal   SuccessfulMountVolume  15m               kubelet, kubeminion-03  MountVolume.SetUp succeeded for volume "udev"
  Normal   SuccessfulMountVolume  15m               kubelet, kubeminion-03  MountVolume.SetUp succeeded for volume "procmount"
  Normal   SuccessfulMountVolume  15m               kubelet, kubeminion-03  MountVolume.SetUp succeeded for volume "sparsepath"
  Normal   SuccessfulMountVolume  15m               kubelet, kubeminion-03  MountVolume.SetUp succeeded for volume "config"
  Normal   SuccessfulMountVolume  15m               kubelet, kubeminion-03  MountVolume.SetUp succeeded for volume "openebs-maya-operator-token-mm2vf"
  Warning  Failed                 9m (x3 over 13m)  kubelet, kubeminion-03  Failed to pull image "openebs/node-disk-manager-amd64:v0.1.0-RC2": rpc error: code = Canceled desc = context canceled
  Warning  Failed                 9m (x3 over 13m)  kubelet, kubeminion-03  Error: ErrImagePull
  Normal   BackOff                8m (x5 over 13m)  kubelet, kubeminion-03  Back-off pulling image "openebs/node-disk-manager-amd64:v0.1.0-RC2"
  Warning  Failed                 8m (x5 over 13m)  kubelet, kubeminion-03  Error: ImagePullBackOff
  Normal   Pulling                8m (x4 over 15m)  kubelet, kubeminion-03  pulling image "openebs/node-disk-manager-amd64:v0.1.0-RC2"
  Normal   Pulled                 8m                kubelet, kubeminion-03  Successfully pulled image "openebs/node-disk-manager-amd64:v0.1.0-RC2"
  Warning  BackOff                4m (x13 over 7m)  kubelet, kubeminion-03  Back-off restarting failed container
```

**Comment by dargasudarshan** [comment]
Workaround for this issue is to Disable selinux on all the nodes to get all NDM pods running.

```
openebs       maya-apiserver-8447446bf5-pjmfr                                   1/1       Running             0          40m
openebs       node-disk-manager-66w47                                           1/1       Running             0          40m
openebs       node-disk-manager-b58pd                                           1/1       Running             0          40m
openebs       node-disk-manager-wvxlb                                           1/1       Running             0          40m
openebs       openebs-provisioner-7777f787fb-x7snq                              1/1       Running             0          40m
openebs       openebs-snapshot-operator-74f88657f4-6s5bt                        2/2       Running             0          40m

```

**Comment by PhilippHeuer** [comment]
I just hit the same issue, when it tries to mount `/proc/1/mounts` - i don't want to disable selinux on my server though. Does someone know what selinux rules are required to make this work?

I would be nice to have this limitation described on the installation page of openebs for centos users.

**Comment by RobHofmann** [comment]
> I just hit the same issue, when it tries to mount `/proc/1/mounts` - i don't want to disable selinux on my server though. Does someone know what selinux rules are required to make this work?
> 
> I would be nice to have this limitation described on the installation page of openebs for centos users.

I'm running into the same issue and I dont want to disable SELinux either. Havent found a fix yet.

**Comment by KevinWhalen** [comment]
I grabbed the most recent entry mentioning docker from `/var/log/audit/audit.log` as `trimmed-audit.log`, then did the following to create a new SELinux policy.

    sudo audit2allow -i trimmed-audit.log -m openebs-storage > openebs-storage.te

openebs-storage.te

>     module openebs-storage 1.0;
> 
>     require {
>         type init_t;
>         type container_runtime_t;
>         class file mounton;
>     }
> 
>     #============= container_runtime_t ==============
>     allow container_runtime_t init_t:file mounton;

    sudo checkmodule -M -m -o openebs-storage.mod openebs-storage.te
    sudo semodule_package -o openebs-storage.pp -m openebs-storage.mod
    sudo semodule -i openebs-storage.pp

**Note:** This was fine for 18.06, but I have a mix of nodes that are 18.09. For those there is a [context issue](https://github.com/docker/for-linux/issues/547) that required a [work-around](https://github.com/docker/for-linux/issues/547#issuecomment-451978918), but it should be [fixed](https://github.com/docker/for-linux/issues/547#issuecomment-478959515) in the next release of `container-selinux`.

    sudo mv /usr/bin/containerd /usr/bin/docker-containerd
    sudo ln -s /usr/bin/docker-containerd /usr/bin/containerd
    sudo restorecon -RvF /usr/bin/
    sudo systemctl restart containerd

**Comment by akhilerm** [comment]
@KevinWhalen @RobHofmann Can you try with the latest release of NDM, (`imageTag: v0.3.5`). We have fixed the issue, now you can run without disabling Selinux.

**Comment by KevinWhalen** [comment]
@akhilerm, I tried, but with no luck.

I was careful to purge everything (storage classes, volumes, etc.). I removed the policy module and tested that I still got the SELinux denial with v0.3.4. Purged again, then deployed with v0.3.5. Sorry, but it did not work. I tried twice, but it was pretty clear it was not working the first time. 

This is the image it pulled: `quay.io/openebs/node-disk-manager-amd64:v0.3.5`.

The audit message with v0.3.4

> type=AVC msg=audit(**1556552477.678:218596**): avc:  denied  { **mounton** } for  pid=836804 comm="runc:[2:INIT]" path="/var/lib/docker/overlay2/a6a68124c9d89492c74f6bb37391ba3886adf7c2aacbbc45b65a9d52b7cbd307/merged/host/mounts" dev="proc" ino=20723 scontext=system_u:system_r:container_runtime_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=file permissive=0

The audit message with v0.3.5:

> type=AVC msg=audit(**1556552928.670:218915**): avc:  denied  { **mounton** } for  pid=843043 comm="runc:[2:INIT]" path="/var/lib/docker/overlay2/7cb1d0488377041ae90ec9633f1ff00c5e2e8f95dea8412c25b2fc08012d33b9/merged/host/mounts" dev="proc" ino=20723 scontext=system_u:system_r:container_runtime_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=file permissive=0

**Comment by akhilerm** [comment]
@KevinWhalen oops. I missed one point. You need to make a small edit in the hostpath.
It's updated in the latest OpenEBS charts at [#369](https://github.com/openebs/charts/blob/9313c439964653a33e7ba315c1fe3f26fd9965b5/docs/openebs-operator-0.8.2.yaml#L369) and [#406](https://github.com/openebs/charts/blob/9313c439964653a33e7ba315c1fe3f26fd9965b5/docs/openebs-operator-0.8.2.yaml#L406)

**Comment by KevinWhalen** [comment]
@akhilerm, sorry, I am not seeing how to edit those. I was using the Helm catalog (kubernetes-charts.storage.googleapis.com), but I also tried deprecated github.com/openebs/charts but I am not sure if I added that catalog correctly. I guess I should also note that I have been running this through Rancher v2.2 and not directly with Helm and Kubernetes.

**Comment by akhilerm** [comment]
@KevinWhalen , After installing, you could use `kubectl edit ds openebs-ndm` from the master node to edit the Daemonset spec.

**Comment by KevinWhalen** [comment]
@akhilerm, I am somewhat new to kubernetes, so it took me a minute to figure out contexts and namespaces with `kubectl` (cluster: external, app: storage, namespace: openebs).

For my setup, I believe this got me into the correct daemonset, but the specification was much shorter and did not seem to have anything that could matched the changes of https://github.com/openebs/charts/commit/9313c439964653a33e7ba315c1fe3f26fd9965b5

    kubectl edit ds storage-openebs-ndm --context external --namespace openebs

I also tried it with the context of different machines in the cluster, but it appeared to be the same.

[daemonset.storage-openebs-ndm.openebs.external.txt](https://github.com/openebs/node-disk-manager/files/3132073/daemonset.storage-openebs-ndm.openebs.external.txt)

**Comment by akhilerm** [comment]
@KevinWhalen from the `daemonset.storage-openebs-ndm.openebs.external.txt` file you have provided, you can find the above said lines under `volumeMounts` and `volumes`.

**Comment by akhilerm** [comment]
@KevinWhalen  you could also join the [OpenEBS](https://openebs.io/join-our-community) community channel on slack, for quick responses and troubleshooting.

**Comment by KevinWhalen** [comment]
You are correct. I ignored the dash (-) and looked at pairs of "name" followed by "mountPath" instead of object keys per list entry. My bad.

Success! The failing pod restarted with that change and successfully deployed without needing special SELinux policy configurations.

**Comment by akhilerm** [comment]
FIxed by mounting `/proc` directory of the host inside the container
