### ISSUE TITLE
Integration test for path filter

### ISSUE THREAD

**Issue by Akash4927** [openebs/node-disk-manager#88]

**Comment by akhilerm** [comment]
@Akash4927 Can you give a little detail about the issue/test. 
I am willing to take it up.

**Comment by a4abhishek** [comment]
@akhilerm please check [integration_test/ginkgo_integration_test.go](https://github.com/openebs/node-disk-manager/blob/master/integration_test/ginkgo_integration_test.go). This file gets executed when you trigger Integration Test for NDM.

**Comment by shovanmaity** [comment]
> @Akash4927 Can you give a little detail about the issue/test.
> I am willing to take it up.

@akhilerm  Path filter use disk path to filter out disk's in node-disk-manager.yaml you can find one configmap and there is one entry for path filter configuration. There you can enable and disable this filter. You can also provide include and exclude filter to fit your use cases. If you provide include value then ndm will create disk cr for those disk which have path matching with given pattern in config map. If you provide exclude value then ndm will not create disk cr for those disk which have path matching with given pattern in config map. You can design one test plans for various use cases and put them in this issue. Then you can implement those tests.

**Comment by shovanmaity** [comment]
Assume I have 2 physical scsi disk and 2 virtual disk.
 Scsi disk's path starts with `sd` so path of 2 disks will be like `/deb/sdx` and `/dev/sdx`. Virtual disk's path starts with `vd` so path of 2 disks will be like `/deb/vdx` and `/dev/vdx` .
We want only scsi disk should be managed by ndm then we can specify `sd` in include section of configmap.
If we want only virtual disk should not be managed by ndm then you can specify `vd` in exclude section of configmap.
We can provide multiple value in include and exclude section suppose if we want to avoid loop, ram , rom disk's entry in etcd then wecan specify `loop,sr,ram` in exclude esction.

**Comment by shovanmaity** [comment]
let me know if you have any question related path filter. and try to post test case plan here then implement it using [citf.](https://github.com/openebs/citf)

**Comment by akhilerm** [comment]
thanks @shovanmaity . will update soon about the test plan.

**Comment by akhilerm** [comment]
Do I need to create a separate package for the path_filter test? Or include the test functions in `ndm_util` ?

Then I need to describe the integration test in `ginkgo_integration_test.go`. Is this the method I should follow?

**Comment by akhilerm** [comment]
@shovanmaity @a4abhishek 
The steps I figured out for the test : 

1. Call `YAMLPrepare()` to make necessary changes in YAML for exclude and include in filter configs.
2. trigger the integration test.
3.  Check for whether the disks are attached or not using `MatchDisksOutsideAndInside()`

The test cases. : `GetLsblkOutputOnHost()` to get the list of disks present on host. Take each one from the list and modify the include/exclude in the yaml file. Run the test. eg : /dev/sda, /dev/sr0 in YAML and check that those are attached to the node / disk containers are created.
Test with same path in both include and exclude to check behavior. 
Make sure disks in exclude are not in the list of created containers.

This is the current plan, I have identifed. Please give suggestions, so that it can be improved.

**Comment by shovanmaity** [comment]
> 3\. Check for whether the disks are attached or not using

@akhilerm add some precheck like if ndm is running delete it. Then modify yaml and create ndm again with modified yaml then quarry for disk object and check path for disk cr's. Add one cleanup at the end to delete all disk resources and ndm pod. High level steps looks good to me. @a4abhishek please review it once.

**Comment by akhilerm** [comment]
@shovanmaity  the creation and cleaning will  be done by `_BeforeSuite` and `_AfterSuite` right, if Iam triggering the test from  [ginkgo_integration_test](https://github.com/openebs/node-disk-manager/blob/master/integration_test/ginkgo_integration_test.go) ?

**Comment by akhilerm** [comment]
This issue has been fixed in #172 .

**Comment by kmova** [comment]
yes!
