### ISSUE TITLE
Fix lint errors in types.go file

### ISSUE THREAD

**Issue by qiell** [openebs/node-disk-manager#94]
File: [types.go](https://github.com/openebs/node-disk-manager/blob/master/pkg/apis/openebs.io/v1alpha1/types.go)

```
Line 30: warning: exported type DiskStatus should have comment or be unexported (golint)
Line 34: warning: exported type DiskCapacity should have comment or be unexported (golint)
Line 48: warning: comment on exported type DiskDevLink should be of the form "DiskDevLink ..." (with optional leading article) (golint)
```

**Comment by rafa-acioly** [comment]
i'll take this one! :)

**Comment by Akash4927** [comment]
Awesome @rafa-acioly, Thank you

**Comment by arshadkazmi42** [comment]
@Akash4927 is it still open?

**Comment by Akash4927** [comment]
@arshadkazmi42 No, I think @rafa-acioly already raised a PR for this.

**Comment by arshadkazmi42** [comment]
@Akash4927 I thought @rafa-acioly has not replied for a week, so its open. No issues, I will explore other open issues 👍

**Comment by Iamchotusri** [comment]
i will work on this issues

**Comment by Iamchotusri** [comment]
Signed-off-by: sijith iamchotusri@gmail.com

**Comment by sourabh1031** [comment]
@qiell can i work on this

**Comment by akhilerm** [comment]
Sure @sourabh1031 . Go Ahead.

**Comment by akhilerm** [comment]
This issue is irrelevant now as the codebase has changed and disk type is removed.
