### ISSUE TITLE
Fix lint error in sparsefilegenerator.go file

### ISSUE THREAD

**Issue by qiell** [openebs/node-disk-manager#97]
File: [sparsefilegenerator.go](https://github.com/openebs/node-disk-manager/blob/master/cmd/controller/sparsefilegenerator.go)

```
Line 48: warning: exported const ENV_SPARSE_FILE_DIR should have comment (or a comment on this block) or be unexported (golint)
```

**Comment by Akash4927** [comment]
@albertogviana PR is already raised for this

**Comment by AraanBranco** [comment]
@Akash4927 is it still open?

**Comment by ShaakhaBrahma** [comment]
am working on this issue

**Comment by ShaakhaBrahma** [comment]
Signed-off-by: ShaakhaBrahma <vatsavatsi777@protonmail.com>

**Comment by ShaakhaBrahma** [comment]
Signed-off-by: ShaakhaBrahma <vatsavatsi777@protonmail.com>

**Comment by akhilerm** [comment]
Changes are merged as part of multiple PRs
